### ISSUE TITLE
默认zsh在 git 仓库里会显示 git branch和git status 的功能被覆盖了

### ISSUE THREAD

**Issue by ZhuFengdaaa** [skywind3000/vim#1]
默认zsh在 git 仓库里会显示当前的git branch（红字）和git status，我把你的zshrc添加在我的zshrc后面之后，这个功能没有了，变成了这样

```
username@machine10:~%
```

**Comment by skywind3000** [comment]
antigen apply 前面加一句 antigen theme fishy，或者注释掉修改 PS1 那一行。

不过我自己非常不喜欢 git branch 的信息，把我电脑拖慢了不少。大部分时候我也不关心branch，要看branch敲几个字母就够了。

**Comment by ZhuFengdaaa** [comment]
注释掉修改 PS1 那一行没用，antigen apply 前加 antigen theme fishy 有用，而且git branch 放在右边了，很简洁。多谢～

请问修改PS1那串字符代表什么意思？

**Comment by skywind3000** [comment]
删除默认 oh-my-zsh 的提示。
