### ISSUE TITLE
prompt 无法修改

### ISSUE THREAD

**Issue by zhyiyu** [skywind3000/vim#12]
你好，谢谢你分享的配置。

我有个问题，我想修改 prompt, 所以我把[配置文件](https://github.com/skywind3000/vim/blob/master/etc/zshrc.zsh#L43)里 `export PS1` 的那一行改成了

```
export PS1="%T, %~: "
```

但是每次重新打开终端之后，都需要重新 source 一下，否则 prompt 就还是之前的样子，不知道为什么。

谢谢！

**Comment by zhyiyu** [comment]
今天忽然就可以了，也不知道为什么，我用的是

```zsh
export PS1="%T, %1~: "
```

**Comment by zhyiyu** [comment]
现在的情况是，如果 `source` 一下，prompt 就会正确显示，但是新开的 terminal 就需要重新 `source`, 不知道为什么。

**Comment by skywind3000** [comment]
你要写到 bashrc 里，固化起来

**Comment by zhyiyu** [comment]
谢谢啊，现在可以啦。

先在 `~/.bashrc` 写 `export PS1="%T, %1~: "`, 然后在 `~/.zshrc` 里面加入 `source ~/.bashrc`, 最后 `source ~/.zshrc` 就可以啦。
