### ISSUE TITLE
韦大，这里分号(;)是不是多余了？

### ISSUE THREAD

**Issue by nnop** [skywind3000/vim#19]
https://github.com/skywind3000/vim/blob/99413dda24a82315809b367b9b4780daf2480592/asc/unix.vim#L18

**Comment by skywind3000** [comment]
不多于，是你自己没理解，

`./.tags;` 的意思是在当前文件所在目录，以及所有上级目录搜索 .tags 文件。分号在这里是向上递归的意思。

**Comment by nnop** [comment]
了解了，多谢~
