### ISSUE TITLE
zshrc.zsh 报错  "FAST_HIGHLIGHT: assignment to invalid subscript range"

### ISSUE THREAD

**Issue by ghtz08** [skywind3000/vim#22]
在 .zshrc 里直接 source [zshrc.zsh](https://github.com/skywind3000/vim/blob/5127bce59d31ad941b8a792bbac38233502b71d8/etc/zshrc.zsh#L142)，登录后出现的最后一个错误提示是：`FAST_HIGHLIGHT: assignment to invalid subscript range`。前面的输出是
```
Installing sorin-ionescu/prezto!...
Installing rupa/z!...
Installing Vifon/deer!...
Installing zdharma/fast-syntax-highlighting!...
Installing willghatch/zsh-cdr!...
Installing sorin-ionescu/prezto... Error! Activate logging and try again.
Installing rupa/z... Error! Activate logging and try again.
Installing Vifon/deer... Error! Activate logging and try again.
Installing zdharma/fast-syntax-highlighting... Error! Activate logging and try again.
Installing willghatch/zsh-cdr... Error! Activate logging and try again.
```

环境：
zsh 5.4.2 (x86_64-ubuntu-linux-gnu)
容器 ubuntu:18.04

**Comment by skywind3000** [comment]
不要用 zshrc 了，用 prezto.zsh

**Comment by ghtz08** [comment]
> 不要用 zshrc 了，用 prezto.zsh

为什么？

**Comment by skywind3000** [comment]
因为 zshrc.zsh 我已经很久没维护了。

**Comment by ghtz08** [comment]
好的，谢谢

**Comment by ghtz08** [comment]
我用了 [prezto.zsh](https://raw.githubusercontent.com/skywind3000/vim/master/etc/prezto.zsh) 里的内容，问题依然存在

```
Installing sorin-ionescu/prezto!...
Installing rupa/z!...
Installing Vifon/deer!...
Installing zdharma/fast-syntax-highlighting!...
Installing willghatch/zsh-cdr!...
Installing sorin-ionescu/prezto... Error! Activate logging and try again.
Installing rupa/z... Error! Activate logging and try again.
Installing Vifon/deer... Error! Activate logging and try again.
Installing zdharma/fast-syntax-highlighting... Error! Activate logging and try again.
Installing willghatch/zsh-cdr... Error! Activate logging and try again.
prezto.zsh:142: FAST_HIGHLIGHT: assignment to invalid subscript range
```

**Comment by skywind3000** [comment]
你的 zsh 太老了？我是 5.7.1 了，homebrew install 一个新的试试？

**Comment by ghtz08** [comment]
我用的 ubuntu 18.04，apt 只能安装 zsh 5.4.2 的版本，从源构建的话我担心我会搞砸。

这个问题应该和我的环境有关系，因为我在其它系统上即使用 zshrc.zsh 也没有遇到这个问题。要排除我的环境问题似乎有点困难，我对 zsh 的配置不熟悉，能否给我点提示好让我自己尝试去解决。
我有下面这两个问题：
1. 为什么 `FAST_HIGHLIGHT[chroma-git]="chroma/-ogit.ch"` 会报错？
2. 对于 `Error! Activate logging and try again.`，我该怎么 `Activate logging`？生成的 log 文件是 `~/.antigen/debug.log` 吗？

对我来说第 2 个问题更关键，因为注销掉 `FAST_HIGHLIGHT[chroma-git]="chroma/-ogit.ch"` 我不容易感知到副作用。

**Comment by skywind3000** [comment]
你安装个 linux [homebrew](https://brew.sh/)，里面有最新的各种包。而且安装 homebrew 不需要 root 权限，可以安装在你自己的目录下，不会破坏你的系统的：

    brew install zsh

就有了，慢的话，你自己加个代理，比如

    ALL_PROXY=socks5://localhost:1080 HTTPS_PROXY=socks5://localhost:1080   brew install zsh

**Comment by ghtz08** [comment]
我通过 homebrew 安装了 zsh 5.8.1，解决了问题。之后我再卸载 zsh 5.8.1，继续使用之前的 zsh 5.4.2，没有出现之前的错误。

看起来像我的环境缺了点什么，因为 docker 的 ubuntu 是精简的系统。

**Comment by ghtz08** [comment]
设置环境变量 [ANTIGEN_LOG](https://github.com/zsh-users/antigen/wiki/Configuration#general) 后，通过 antigen 的日志文件发现是因为缺少 `ca-certificates` 导致的，安装后就成功了。

目前还有个小问题，但它造成的影响并没有被我感知到，最后会输出`_z_dirs:2: no such file or directory: /home/name/.z`。
