### ISSUE TITLE
E474: 无效的参数: cscopequickfix

### ISSUE THREAD

**Issue by LMCallMe** [skywind3000/vim#6]
处理 ..../vim/plugin/gutentags_plus.vim 时发生错误:

$ 第   11 行:
$ E474: 无效的参数: cscopequickfix=s+,c+,d+,i+,t+,e+,g+,f+,a+
$ 请按 ENTER 或其它命令继续

从 http://www.yeolar.com/media/doc/vimcdoc/html/if_cscop.html#cscopequickfix 可知：

'cscopequickfix' 设定是否使用 quickfix 窗口来显示 cscope 结果。这是一组用逗号
分隔的值。每个值可以代表一个 |cscope-find| 命令 (s、g、d、c、t、e、f 或 i) 加
一个标志位 (+、- 或 0)。
'+' 表示结果必须被添加到 quickfix 窗口中。'-' 表示清除上次的结果，'0' 或命令本
身不存在表示不使用 quickfix。搜索从字符串首开始直到命令第一次出现时结束。缺省
值是 "" (不使用 quickfix 窗口)。下面是个可能有用的值:
        :set cscopequickfix=s-,c-,d-,i-,t-,e-

然后， 我去除了 a+ 选项， 就不报错了，不知是什么原因

**Comment by skywind3000** [comment]
那你就先去除a嘛。

**Comment by skywind3000** [comment]
你的vim版本太老了

**Comment by skywind3000** [comment]
我更新了，加入了版本判断，但是你的vim真的太老了，8.1都发布了，你不会还在 7.4？？

**Comment by skywind3000** [comment]
方便以后更新，我把这个脚本拎出来了：

https://github.com/skywind3000/gutentags_plus
